openapi: 3.0.1
info:
  title: Authorizer
  description: T
  termsOfService: "http://swagger.io/terms/"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.3
paths:
  /user/login:
    get:
      summary: Logs user into the system
      operationId: loginUser
      parameters:
        - name: email
          in: query
          description: The user email for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: string
  /user/register:
    post:
      summary: register user into the system
      operationId: registerUser
      requestBody:
        description: user daten
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    User:
      title: User
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstNameKid:
          type: string
        secondNameKid:
          type: string
        group:
          type: string
