openapi: 3.0.1
info:
  title: Authorizer
  description: T
  termsOfService: "http://swagger.io/terms/"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.3
paths:
  /user/login:
    get:
      summary: Logs user into the system
      operationId: loginUser
      parameters:
        - name: email
          in: query
          description: The user email for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        "301":
          description: infastructure problem
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Invalid username/password supplied
          content:
            application/json:
              schema:
                type: string
        "404":
          description: user does not exist
          content:
            application/json:
              schema:
                type: string
  /user/logout:
    get:
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
          content: {}
